### PR TITLE
Installation instructions

### PR DESCRIPTION
**Pull request by phunehehe**
I converted INSTALL to Markdown, added a bit of formatting and a little rewording.

### CODE REVIEW

**Comment by uakfdotb** [comment]
Looks good, thanks.

**Comment by phunehehe** [comment]
Err I'm sorry I didn't see this sooner, but what is the relationship between this repo and ajgon/gpg-mailgate? There seem to be activities in both. Is either repo an "upstream"?

**Comment by uakfdotb** [comment]
The main purpose of this repository is for the gpg-mailgate-web web interface, so that you can put it on your web server and have mail sent from a web application be encrypted for users who upload their PGP key. This makes it easy for people running web applications to add PGP support since no change in the web application is needed.

The web application can also be used for incoming email, since gpg-mailgate will encrypt both outgoing/incoming.

**Comment by phunehehe** [comment]
Ah I got it now, I guess I should also send a PR against the other repo. Thanks.

**Pull request merged**
